[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-args=-fuse-ld=lldcarg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
